### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by MaybeSacred** [swlaschin/fsharpforfunandprofit.com#1]
Some links appear to be broken in [Why Use F#](https://github.com/swlaschin/fsharpforfunandprofit.com/blob/master/why-use-fsharp/index.md): "Many common programming tasks are much simpler in F#. This includes things like creating and using [/posts/conciseness-type-definitions/](complex type definitions), doing list processing, [/posts/convenience-types/](comparison and equality), state machines, and much more."

This is a fantastic website btw!

**Comment by swlaschin** [comment]
Thanks for letting me know about the errors! Fixed now!
