### ISSUE TITLE
Newsletter Mailchimp issue

### ISSUE THREAD

**Issue by mintymac** [swlaschin/fsharpforfunandprofit.com#23]
Firstly, I would like to commend you on this book.  I'm not writing in F# ( elixir and elm at the moment ) but your explanations address how to think about the problem vs how to write code.  Thank you again for all of your insight.  

I enjoyed your book so much that I would like to subscribe to your newsletter...but I receive this message.  
![screen shot 2019-01-27 at 7 11 09 pm](https://user-images.githubusercontent.com/133960/51809533-55532900-2267-11e9-9e7c-93460215dd29.png)

**Comment by swlaschin** [comment]
(sorry the long delay in responding)

Yes, I added a link but I never did use it. I'm going to remove that link!
