### ISSUE TITLE
The properties for a sorted list are insufficient

### ISSUE THREAD

**Issue by Arshia001** [swlaschin/fsharpforfunandprofit.com#26]
In "Choosing properties for property-based testing", it says a sorted list should be:

>In fact, these two properties, adjacent pairs from a list should be ordered and a sorted list has same contents as the original list should indeed ensure that any implementation is correct.

This (as implemented in the article by checking the length and permutation-ness) is true of a list without duplicates, and the EDFH would have a hard time implementing such an algorithm, but this case passes the tests and is wrong:

`sort [2; 2; 1; 3] -> [1; 1; 2; 3]`

**Comment by swlaschin** [comment]
(Sorry for the delay in responding) 

Maybe I don't understand, but in your example the second list is not a permutation of the first list, so it would fail that property.

**Comment by Arshia001** [comment]
OK, I have no idea what I was thinking when I posted this issue. Must have been mentally tired from all the new concepts of functional programming, which was proving difficult at the time... I learned all of it reading your book BTW, thank you very much for such a great book!

**Comment by swlaschin** [comment]
Ok, no problem! Thanks!
