### ISSUE TITLE
Subscribe to newsletter is not working

### ISSUE THREAD

**Issue by simonvane** [swlaschin/fsharpforfunandprofit.com#36]
Clicking subscribe on https://fsharpforfunandprofit.com/subscribe.html 
Goes to https://fsharpforfunandprofit.us7.list-manage.com/subscribe/post?u=4da12e20f26ec7bac54728cb9&id=f0380695b6
Displaying:
![image](https://user-images.githubusercontent.com/1423185/65417888-0d36d700-ddf3-11e9-9021-3a91b36ee05f.png)

"Failed to load resource: the server responded with a status of 404 ()" error displays in the console in developer tools.

**Comment by swlaschin** [comment]
Yes, I added a link but I never did use it. I'm going to remove that link!

**Comment by simonvane** [comment]
OK
