### ISSUE TITLE
ROP video links broken

### ISSUE THREAD

**Issue by joehodsdon** [swlaschin/fsharpforfunandprofit.com#54]
Hi -- the 3 links to your ROP videos are broken on page https://fsharpforfunandprofit.com/rop :

- https://goo.gl/Lv5ZAo  (https://vimeo.com/113707214)
- http://vimeo.com/97344498
- https://skillsmatter.com/skillscasts/4964-railway-oriented-programming

Thanks for providing this resource to the community!

**Comment by swlaschin** [comment]
Sorry for the delay getting back to you! These links have fixed themselves now! :)
