### ISSUE TITLE
eBook download 

### ISSUE THREAD

**Issue by hikarisakamoto** [swlaschin/fsharpforfunandprofit.com#65]
Hey!
I'm getting redirected to GitBook main page when trying to download the ebook PDF (also end-up trying for ePub and Kindle and got the same problem).

Thanks for your time!

**Comment by swlaschin** [comment]
Thanks for the comment. The ebook of the site is not currently available, and I've now updated the site to make it clear. 

I will try to make a new ebook in the future! Thanks!
