### ISSUE TITLE
Union type without Of in Low overhead type definitions example

### ISSUE THREAD

**Issue by RHRafi009** [swlaschin/fsharpforfunandprofit.com#71]
I was following this site and when at this [page](https://fsharpforfunandprofit.com/posts/conciseness-type-definitions/) I've found this problem,
There is a union type of Address which consists of three other types.
`type Address = USAddress | UKAddress | InternationalAddress`
The problem is compiler does not understand that these three are itself another type and thus I can not assign a UkAddress variable in an Address variable. 
For now, I've found a workaround for this. which is like that,
`type Address = UsAddress of USAddress | UkAddress of UKAddress | InternationalAddress of InternationalAddress`
Also, I think if there is a Customer variable with some dummy data then it would be much more understandable.

**Comment by swlaschin** [comment]
Fixed now. Thanks!
