### ISSUE TITLE
Broken link in recursive types and fold series

### ISSUE THREAD

**Issue by thanasis31** [swlaschin/fsharpforfunandprofit.com#79]
Hello,

First of all, thanks for the excellent content.

The msdn links for the fold and fold back documentation are broken for this [page](https://fsharpforfunandprofit.com/posts/recursive-types-and-folds-3/).

First broken link:
Text: If we compare the signature with the List.fold documentation we ....
Correct link (suggestion): 
https://fsharp.github.io/fsharp-core-docs/reference/fsharp-collections-listmodule.html#fold

Secondbroken link:
Text: Again, if we compare the signature with the List.foldBack documentation .... 
Correct link (suggestion): 
https://fsharp.github.io/fsharp-core-docs/reference/fsharp-collections-listmodule.html#foldBack

**Comment by swlaschin** [comment]
Thanks for catching this. Fixed!
