### ISSUE TITLE
Broken Link in Using F# for development and devops scripts

### ISSUE THREAD

**Issue by voh83** [swlaschin/fsharpforfunandprofit.com#80]
In  the paragraph:

A hidden agenda, of course, is that once your fellow developers get a chance to play with F#, they’ll be hooked, and you’ll be one step closer to using **F# end to end!**

the link to https://colinbul.wordpress.com/2013/02/23/f-end-to-end/ is no longer available.

**Comment by swlaschin** [comment]
Thanks for catching this. I replaced that link with archive.org but lots of the links on that page have rotted by now :(
