### ISSUE TITLE
Broken Link  https://fsharpforfunandprofit.com/posts/concurrency-reactive/

### ISSUE THREAD

**Issue by voh83** [swlaschin/fsharpforfunandprofit.com#82]
Hi Scott, 

There is a broken link in the following section of fsharpforfunandprofit.

https://fsharpforfunandprofit.com/posts/concurrency-reactive/

the broken link is correspondind to the  [Observable module](https://msdn.microsoft.com/visualfsharpdocs/conceptual/control.observable-module-%5bfsharp%5d) in the summary section.

I suggest to replace it with https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2010/ee370313(v=vs.100)?redirectedfrom=MSDN  but microsfot indicates that is no longer update this content regularly.

Thanks for your wonderful content

**Comment by swlaschin** [comment]
Thanks for catching this! I fixed the link using your suggestion.
